e-commerce/Project.abznotebook.Web/Areas/Member/Models/AddressViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.AccessControl;
using System.Threading.Tasks;

namespace Project.abznotebook.Web.Areas.Member.Models
{
    public class AddressViewModel
    {
        public string Title { get; set; }

        public string AddressLine { get; set; }

        public string City { get; set; }

        public string District { get; set; }

        public string Neighborhood { get; set; }

        public string PostalCode { get; set; }

    }
}

e-commerce/Project.abznotebook.Web/Areas/Member/Controllers/AddressController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using Project.abznotebook.Business.Interfaces;
using Project.abznotebook.Entities.Concrete;
using Project.abznotebook.Web.Areas.Member.Models;

namespace Project.abznotebook.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class AddressController : Controller
    {
        private readonly IAddressService _addressService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IAppUserService _appUserService;
        private readonly SignInManager<AppUser> _signInManager;

        public AddressController(IAddressService addressService, IAppUserService appUserService, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _addressService = addressService;
            _appUserService = appUserService;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var appUser = await _userManager.GetUserAsync(User);
            return View(_addressService.GetAddressesByUserId(appUser.Id));
        }

        [HttpGet]
        public IActionResult AddAddress()
        {
            return View(new AddAddressViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAddress(AddAddressViewModel model)
        {

            var appUser = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                _addressService.Save(new Address()
                {
                    Title = model.Title,
                    AddressLine = model.AddressLine,
                    City = model.City,
                    District = model.District,
                    Neighborhood = model.Neighborhood,
                    PostalCode = model.PostalCode,
                    AppUserId = appUser.Id
                });

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditAddress(int addressId)
        {
            var appUser = await _userManager.GetUserAsync(User);

            try
            {
                var selectedAddress = _addressService.GetAddressesByUserId(appUser.Id).Single(I => I.Id == addressId);
                return View(selectedAddress);
            }
            catch (Exception)
            {
                return NotFound();
            }

            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditAddress(Address address)
        {

            if (ModelState.IsValid)
            {
                _addressService.Update(new Address()
                {
                    Title = address.Title,
                    City = address.City,
                    District = address.District,
                    AddressLine = address.AddressLine,
                    PostalCode = address.PostalCode,
                    Neighborhood = address.Neighborhood,
                    Id = address.Id,
                    AppUserId = address.AppUserId
                });

                return RedirectToAction("Index");
            }

            

            return View(address);
        }

    }
}

e-commerce/Project.abznotebook.Web/Areas/Member/Views/Address/AddAddress.cshtml
@model Project.abznotebook.Web.Areas.Member.Models.AddAddressViewModel

@{
    ViewData["Title"] = "AddAddress";
    Layout = "~/Areas/Member/Views/Shared/_StandartLayout.cshtml";
}

<div style="border-bottom:1px solid lightgray; padding-bottom:30px">
    <h1 style="width:100%; text-align:center">Adres Ekle</h1>
</div>

<div class="container" style="width:50%; text-align:left">
    <div class="row my-4">
        <div class="card-body">
            <form asp-action="AddAddress">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label">Adres Başlığı</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="City" class="control-label">Şehir</label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="District" class="control-label">İlçe</label>
                    <input asp-for="District" class="form-control" />
                    <span asp-validation-for="District" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="AddressLine" class="control-label">Adres</label>
                    <input asp-for="AddressLine" class="form-control" />
                    <span asp-validation-for="AddressLine" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Neighborhood" class="control-label">Mahalle</label>
                    <input asp-for="Neighborhood" class="form-control" />
                    <span asp-validation-for="Neighborhood" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PostalCode" class="control-label">Posta Kodu</label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <div style="width:100%; text-align:right">
                        <a asp-action="Index" class="btn btn-primary pr-4">Adreslerime Dön</a>
                        @*<input type="submit" value="Ekle" class="btn btn-primary text-right mt-3" />*@
                        <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Ekle</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

e-commerce/Project.abznotebook.Web/Areas/Member/Views/Address/EditAddress.cshtml
@model Address
@{
    ViewData["Title"] = "EditAddress";
    Layout = "~/Areas/Member/Views/Shared/_StandartLayout.cshtml";
}

<div style="border-bottom:1px solid lightgray; padding-bottom:30px">
    <h1 style="width:100%; text-align:center">Adres Ekle</h1>
</div>

<div class="container" style="width:50%; text-align:left">
    <div class="row my-4">
        <div class="card-body">
            <form asp-action="EditAddress">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="AppUserId" class="control-label" hidden>Adres Başlığı</label>
                    <input asp-for="AppUserId" class="form-control" value="@Model.AppUserId" hidden />
                    <span asp-validation-for="AppUserId" class="text-danger" hidden></span>
                </div>

                <div class="form-group">
                    <label asp-for="Id" class="control-label" hidden>Adres Başlığı</label>
                    <input asp-for="Id" class="form-control" value="@Model.Id" hidden />
                    <span asp-validation-for="Id" class="text-danger" hidden></span>
                </div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label">Adres Başlığı</label>
                    <input asp-for="Title" class="form-control" value="@Model.Title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="City" class="control-label">Şehir</label>
                    <input asp-for="City" class="form-control" value="@Model.City" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="District" class="control-label">İlçe</label>
                    <input asp-for="District" class="form-control" value="@Model.District" />
                    <span asp-validation-for="District" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="AddressLine" class="control-label">Adres</label>
                    <input asp-for="AddressLine" class="form-control" value="@Model.AddressLine" />
                    <span asp-validation-for="AddressLine" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Neighborhood" class="control-label">Mahalle</label>
                    <input asp-for="Neighborhood" class="form-control" value="@Model.Neighborhood" />
                    <span asp-validation-for="Neighborhood" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PostalCode" class="control-label">Posta Kodu</label>
                    <input asp-for="PostalCode" class="form-control" value="@Model.PostalCode" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <div style="width:100%; text-align:right">
                        <a asp-action="Index" class="btn btn-primary pr-4">Vazgeç</a>
                        <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

e-commerce/Project.abznotebook.Web/Areas/Member/Views/Address/Index.cshtml
@model List<Address>

<div style="border-bottom:1px solid lightgray; padding-bottom:30px">
    <h1 style="width:100%; text-align:center">Adreslerim</h1>
</div>

@{
    if (Model.Count != 0)
    {
        <div style="width:100%; border-bottom:1px solid lightgray; padding:10px 0; text-align:center; margin-bottom:20px">
            <a class="btn btn-primary" asp-controller="Address" asp-action="AddAddress">Adres Ekle</a>
        </div>
        <div class="container-fluid mt-10 mb-5">
            <div class="row">
                @foreach (var address in Model)
                {
                    <partial name="AddressPartial" model="address" />
                }
            </div>
        </div>
    }
    else
    {
        <div class="mt-4">
            <table class="table table-bordered table-striped" style="font-family: Arial, Helvetica, sans-serif">
                <tr>
                    <td class="text-center" style="color:green; font-size:larger; font-weight:bold">
                        <i class="fa fa-circle-o-notch"></i> Henüz adres kaydetmedin.
                    </td>
                </tr>
                <tr>
                    <td class="text-center"><a asp-controller="Address" asp-action="AddAddress">Buraya</a> tıklayarak adres oluşturabilirsin.</td>
                </tr>
            </table>
        </div>
    }

}