e-commerce/Project.abznotebook.Web/Models/Cart.cs
using System.Collections.Generic;
using System.Linq;
using Project.abznotebook.Entities.Concrete;

namespace Project.abznotebook.Web.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = Lines.Where(p => p.Product.Id == product.Id).FirstOrDefault();

            if (line == null)
            {
                Lines.Add(new CartLine()
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }


        public virtual void RemoveLine(Product product) =>
            Lines.RemoveAll(l => l.Product.Id == product.Id);
        public decimal ComputeTotalValue() => Lines.Sum(e => e.Product.UnitPrice * e.Quantity);
        public virtual void Clear() => Lines.Clear();

    }

    public class CartLine
    {
        public int CartLineId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

e-commerce/Project.abznotebook.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Project.abznotebook.Business.Interfaces;
using Project.abznotebook.Entities.Concrete;
using Project.abznotebook.Web.Models;


namespace Project.abznotebook.Web.Controllers
{
    public class OrderController : Controller
    {

        private readonly IAddressService _addressService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IShipperService _shipperService;
        private readonly IPaymentService _paymentService;
        private readonly Cart _cart;
        private readonly IOrderService _orderService;
        private readonly IOrderDetailService _orderDetailService;

        public OrderController(IAddressService addressService, UserManager<AppUser> userManager, IShipperService shipperService, IPaymentService paymentService, Cart cart, IOrderService orderService, IOrderDetailService orderDetailService)
        {
            _addressService = addressService;
            _userManager = userManager;
            _paymentService = paymentService;
            _shipperService = shipperService;
            _cart = cart;
            _orderService = orderService;
            _orderDetailService = orderDetailService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Checkout()
        {

            OrderViewModel model = new OrderViewModel()
            {
                LinesCount = _cart.Lines.Count
            };

            if (User.Identity.IsAuthenticated)
            {
                var appUser = await _userManager.GetUserAsync(User);
                
                model.Addresses = _addressService.GetAddressesByUserId(appUser.Id);
                model.AddressCollection = new SelectList(model.Addresses, "Id", "Title");
                model.PaymentCollection = new SelectList(_paymentService.GetAllPayments(), "PaymentId", "PaymentType");
                model.ShipperCollection = new SelectList(_shipperService.GetAllShippers(), "Id", "CompanyName");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel model)
        {
            var appUser = await _userManager.GetUserAsync(User);
            model.LinesCount = _cart.Lines.Count;
            model.Addresses = _addressService?.GetAddressesByUserId(appUser.Id);
            model.AddressCollection = new SelectList(model.Addresses, "Id", "Title");
            model.PaymentCollection = new SelectList(_paymentService.GetAllPayments(), "PaymentId", "PaymentType");
            model.ShipperCollection = new SelectList(_shipperService.GetAllShippers(), "Id", "CompanyName");

            if (model.LinesCount == 0)
            {
                ModelState.AddModelError("", "Sepetiniz boş!");
                return View(model);
            }

            Guid orderNumber = Guid.NewGuid();

            if (ModelState.IsValid)
            {
                _orderService.Save(new Order()
                {
                    PaymentId = model.PaymentId,
                    IsShipped = false,
                    CustomerId = appUser.Id,
                    OrderDate = DateTime.Now,
                    OrderNumber = orderNumber,
                    ShipperId = model.ShipperId,
                    AddressId = model.AddressId
                });

                foreach (var cartLine in _cart.Lines)
                {
                    _orderDetailService.Save(new OrderDetail()
                    {
                        ProductId = cartLine.Product.Id,
                        OrderId = _orderService.GetAllOrders().Single(I=>I.OrderNumber.Equals(orderNumber)).Id,
                        Price = cartLine.Product.UnitPrice,
                        Quantity = cartLine.Quantity,
                    });
                }

                int orderId = _orderService.GetAllOrders().Single(I => I.OrderNumber.Equals(orderNumber)).Id;
                return RedirectToAction("Completed", new{orderId = orderId});
            }

            ModelState.AddModelError("", "Seç");

            return View(model);
        }

        public IActionResult Completed(int orderId)
        {
            return View(orderId);
        }



    }
}

e-commerce/Project.abznotebook.Web/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project.abznotebook.Business.Interfaces;
using Project.abznotebook.Entities.Concrete;
using Project.abznotebook.Web.Models;

namespace Project.abznotebook.Web.Pages
{
    public class CartModel : PageModel
    {
        private IProductService _productService;

        public CartModel(IProductService productService, Cart cartService)
        {
            _productService = productService;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int id, string returnUrl, int quantity = 1)
        {
            Product product = _productService.Products.FirstOrDefault(p => p.Id == id);
            Cart.AddItem(product, quantity);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostApplyCoupon(string id, string returnUrl)
        {
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int id, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Product.Id == id).Product);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

    }
}

e-commerce/Project.abznotebook.Web/Pages/Cart.cshtml
@page
@model CartModel

@{
    Layout = "~/Pages/_CartLayout.cshtml";
}
<body>
    <div style="border-bottom:1px solid lightgray; padding-bottom:30px">
        <h1 style="width:100%; text-align:center">Sepetim</h1>
    </div>

    @{
        if (Model.Cart.Lines.Count != 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Ürün</th>
                        <th>Fiyat</th>
                        <th>Adet</th>
                        <th colspan="2" class="text-left">Toplam</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var line in Model.Cart.Lines)
                    {
                        <tr>
                            <td class="text-left">@line.Product.Name</td>
                            <td class="text-left">@line.Product.UnitPrice.ToString("c")</td>
                            <td class="text-center">@line.Quantity</td>
                            <td class="text-left">
                                @((line.Quantity * line.Product.UnitPrice).ToString("c"))
                            </td>
                            <td class="text-center">
                                <form asp-page-handler="Remove" method="post">
                                    <input type="hidden" name="id"
                                           value="@line.Product.Id" />
                                    <input type="hidden" name="returnUrl"
                                           value="@Model.ReturnUrl" />
                                    <button type="submit" class="btn btn-sm btn-outline-danger">
                                        Kaldır
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            <table class="table table-bordered table-striped">
                <tr>
                    <td class="text-right">
                        Ödenecek Tutar : @Model.Cart.ComputeTotalValue().ToString("c")
                    </td>
                </tr>
            </table>
            <div class="text-center">
                <a class="btn btn-outline-success" href="@Model.ReturnUrl">Alışverişe Devam Et</a>
                <a class="btn btn-outline-primary" asp-action="Checkout" asp-controller="Order">Alışverişi Tamamla</a>
            </div>
        }

        else
        {
            <table class="table table-bordered table-striped" style="font-family: Arial, Helvetica, sans-serif">
                <tr>
                    <td class="text-center" style="color:green; font-size:larger; font-weight:bold">
                        <i class="fa fa-shopping-bag"></i> Sepetin şu an boş.
                    </td>
                </tr>
                <tr>
                    <td class="text-center">Sepetini <strong>abz</strong> notebook'un fırsatlarla dolu dünyasından doldurmak için <a href="~/">ürünleri</a> incelemeye başlayabilirsin.</td>
                </tr>
            </table>
        }
    }


</body>

e-commerce/Project.abznotebook.Web/Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/lib/Template/theme/content/test.css" rel="stylesheet" />
    <link href="~/lib/Template/theme/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="~/lib/css/abz-stylesheet.css" rel="stylesheet" />

    <title>abz | Sepetim</title>
    <link href="~/img/favicon_transparent.ico" rel="icon" type="image/x-icon" />
</head>
<body>

    <partial name="NavbarPartial" />

    <div class="container" style="width:80%; margin:0 auto">
        <div class="row" style="margin-top:50px">
            <div class="col-md-12" style="border: solid 1px lightgray; border-radius: 7px; padding-top:50px; padding-bottom:50px; margin-bottom:50px">
                @RenderBody()
            </div>
        </div>
    </div>


</body>
</html>