e-commerce/Project.abznotebook.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.abznotebook.Business.Interfaces;
using Project.abznotebook.Entities.Concrete;
using Project.abznotebook.Web.Base.Common;
using Project.abznotebook.Web.Models;

namespace Project.abznotebook.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IProductService _productService;
        public int pageSize = 6;
        List<FilterViewModel> models = new List<FilterViewModel>();
        public CategoryController(IProductService productService)
        {
            _productService = productService;
        }

        
        [HttpGet]
        public ViewResult Gaming(int productPage = 1, string sortOrder = "", FilterViewModel model=null)
        {
            ProductListViewModel productList = FillProductListViewModelByCategoryId(1, productPage);
            
            if (!string.IsNullOrEmpty(model.SelectedVendor) || !string.IsNullOrEmpty(model.SelectedMemory) || !string.IsNullOrEmpty(model.SelectedProcessor))
            {
                productList.Products = _productService.GetProductsByCategoryId(1);
                productList = FilterLogic.FilterByModel(productList, model);
            }

            productList.PagingInfo.TotalItems = productList.Products.Count();

            ViewBag.OrderStatus = "En İyi Eşleşme";

            switch (sortOrder)
            {
                case "best_match":
                    productList.Products = productList.Products.OrderByDescending(P => P.CreatedDate);
                    ViewBag.OrderStatus = "En İyi Eşleşme";
                    break;

                case "desc_price":
                    productList.Products = productList.Products.OrderByDescending(p => p.UnitPrice);
                    ViewBag.OrderStatus = "Fiyat: Azalan";
                    break;
                case "asc_price":
                    productList.Products = productList.Products.OrderBy(p => p.UnitPrice);
                    ViewBag.OrderStatus = "Fiyat: Artan";
                    break;
            }

            return View(productList);
        }

        [HttpGet]
        public ViewResult HomeOffice(int productPage = 1, string sortOrder = "", FilterViewModel model = null)
        {

            ProductListViewModel productList = FillProductListViewModelByCategoryId(2, productPage);


            if (!string.IsNullOrEmpty(model.SelectedVendor) || !string.IsNullOrEmpty(model.SelectedMemory) || !string.IsNullOrEmpty(model.SelectedProcessor))
            {
                productList.Products = _productService.GetProductsByCategoryId(2);
                productList = FilterLogic.FilterByModel(productList, model);
            }
            productList.PagingInfo.TotalItems = productList.Products.Count();

            ViewBag.OrderStatus = "En İyi Eşleşme";

            switch (sortOrder)
            {
                case "best_match":
                    productList.Products = _productService.GetProductsByCategoryId(2).OrderByDescending(P => P.CreatedDate);
                    ViewBag.OrderStatus = "En İyi Eşleşme";
                    break;

                case "desc_price":
                    productList.Products = _productService.GetProductsByCategoryId(2).OrderByDescending(p => p.UnitPrice);
                    ViewBag.OrderStatus = "Fiyat: Azalan";
                    break;
                case "asc_price":
                    productList.Products = _productService.GetProductsByCategoryId(2).OrderBy(p => p.UnitPrice);
                    ViewBag.OrderStatus = "Fiyat: Artan";
                    break;
            }

            return View(productList);
        }
        
        [HttpGet]
        public ViewResult TwoInOne(int productPage = 1, string sortOrder = "", FilterViewModel model = null)
        {
            ProductListViewModel productList = FillProductListViewModelByCategoryId(3, productPage);


            if (!string.IsNullOrEmpty(model.SelectedVendor) || !string.IsNullOrEmpty(model.SelectedMemory) || !string.IsNullOrEmpty(model.SelectedProcessor))
            {
                productList.Products = _productService.GetProductsByCategoryId(3);
                productList = FilterLogic.FilterByModel(productList, model);
            }
            productList.PagingInfo.TotalItems = productList.Products.Count();

            ViewBag.OrderStatus = "En İyi Eşleşme";

            switch (sortOrder)
            {
                case "best_match":
                    productList.Products = _productService.GetProductsByCategoryId(3).OrderByDescending(P => P.CreatedDate);
                    ViewBag.OrderStatus = "En İyi Eşleşme";
                    break;

                case "desc_price":
                    productList.Products = _productService.GetProductsByCategoryId(3).OrderByDescending(p => p.UnitPrice);
                    ViewBag.OrderStatus = "Fiyat: Azalan";
                    break;
                case "asc_price":
                    productList.Products = _productService.GetProductsByCategoryId(3).OrderBy(p => p.UnitPrice);
                    ViewBag.OrderStatus = "Fiyat: Artan";
                    break;
            }

            return View(productList);
        }

        public ProductListViewModel FillProductListViewModelByCategoryId(int categoryId, int productPage)
        {

            ProductListViewModel productList = new ProductListViewModel()
            {
                Products =
                    _productService.GetProductsByCategoryId(categoryId).OrderBy(p => p.Id).Skip((productPage - 1) * pageSize).Take(pageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = productPage,
                    ItemsPerPage = pageSize,
                },
                FilterTypes = new FilterViewModel()
                {
                    Vendors = _productService.GetProductsByCategoryId(categoryId).Select(I => I.Vendor).Distinct().OrderBy(I => I).ToList(),
                    Memories = _productService.GetProductsByCategoryId(categoryId).Select(I => I.MemoryCapacity).Distinct().OrderBy(I => I).ToList(),
                    Processors = _productService.GetProductsByCategoryId(categoryId).Select(I => I.ProcessorVendor).Distinct().OrderBy(I => I).ToList()
                }
            };

            return productList;
        }
    }
}

e-commerce/Project.abznotebook.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Project.abznotebook.Business.Interfaces;
using Project.abznotebook.Entities.Concrete;
using Project.abznotebook.Web.Models;


namespace Project.abznotebook.Web.Controllers
{
    public class OrderController : Controller
    {

        private readonly IAddressService _addressService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IShipperService _shipperService;
        private readonly IPaymentService _paymentService;
        private readonly Cart _cart;
        private readonly IOrderService _orderService;
        private readonly IOrderDetailService _orderDetailService;

        public OrderController(IAddressService addressService, UserManager<AppUser> userManager, IShipperService shipperService, IPaymentService paymentService, Cart cart, IOrderService orderService, IOrderDetailService orderDetailService)
        {
            _addressService = addressService;
            _userManager = userManager;
            _paymentService = paymentService;
            _shipperService = shipperService;
            _cart = cart;
            _orderService = orderService;
            _orderDetailService = orderDetailService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Checkout()
        {

            OrderViewModel model = new OrderViewModel()
            {
                LinesCount = _cart.Lines.Count
            };

            if (User.Identity.IsAuthenticated)
            {
                var appUser = await _userManager.GetUserAsync(User);
                
                model.Addresses = _addressService.GetAddressesByUserId(appUser.Id);
                model.AddressCollection = new SelectList(model.Addresses, "Id", "Title");
                model.PaymentCollection = new SelectList(_paymentService.GetAllPayments(), "PaymentId", "PaymentType");
                model.ShipperCollection = new SelectList(_shipperService.GetAllShippers(), "Id", "CompanyName");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel model)
        {
            var appUser = await _userManager.GetUserAsync(User);
            model.LinesCount = _cart.Lines.Count;
            model.Addresses = _addressService?.GetAddressesByUserId(appUser.Id);
            model.AddressCollection = new SelectList(model.Addresses, "Id", "Title");
            model.PaymentCollection = new SelectList(_paymentService.GetAllPayments(), "PaymentId", "PaymentType");
            model.ShipperCollection = new SelectList(_shipperService.GetAllShippers(), "Id", "CompanyName");

            if (model.LinesCount == 0)
            {
                ModelState.AddModelError("", "Sepetiniz boş!");
                return View(model);
            }

            Guid orderNumber = Guid.NewGuid();

            if (ModelState.IsValid)
            {
                _orderService.Save(new Order()
                {
                    PaymentId = model.PaymentId,
                    IsShipped = false,
                    CustomerId = appUser.Id,
                    OrderDate = DateTime.Now,
                    OrderNumber = orderNumber,
                    ShipperId = model.ShipperId,
                    AddressId = model.AddressId
                });

                foreach (var cartLine in _cart.Lines)
                {
                    _orderDetailService.Save(new OrderDetail()
                    {
                        ProductId = cartLine.Product.Id,
                        OrderId = _orderService.GetAllOrders().Single(I=>I.OrderNumber.Equals(orderNumber)).Id,
                        Price = cartLine.Product.UnitPrice,
                        Quantity = cartLine.Quantity,
                    });
                }

                int orderId = _orderService.GetAllOrders().Single(I => I.OrderNumber.Equals(orderNumber)).Id;
                return RedirectToAction("Completed", new{orderId = orderId});
            }

            ModelState.AddModelError("", "Seç");

            return View(model);
        }

        public IActionResult Completed(int orderId)
        {
            return View(orderId);
        }



    }
}

e-commerce/Project.abznotebook.Web/Areas/Member/Views/Shared/NavbarPartial.cshtml
@*
    Member's Navbar    
*@

<style>
    .search-item-text {
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }

    .search-item-btn {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }
</style>
<div style="width:100%">
    <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark" style="text-align:center">

        <div class="container" style="width:80%; text-align:center; margin:0 auto">

            <a class="navbar-brand" href="/">
                <img src="~/img/favicon_transparent.png" alt="" width="30" height="30" />
                <span class="fa" style="font-family: Arial, Helvetica, sans-serif">abz notebook</span>
            </a>

            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Category" asp-action="HomeOffice">Notebook<span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Gaming">Oyun Bilgisayarı</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Category" asp-action="TwoInOne">İkisi Bir Arada</a>
                    </li>

                </ul>

                <ul class="navbar-nav">
                    <li>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-0 search-item-text" type="text" placeholder="Bir ürün ara">
                            <button class="btn btn-outline-success my-2 my-sm-0 search-item-btn" type="submit"><span class="fa fa-search"></span></button>
                        </form>
                    </li>
                    <li class="nav-item dropdown dropleft">

                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link" href="#" id="dropdownIdprofil" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="fa fa-user mr-2"></span></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownIdprofil">
                                <a class="dropdown-item" href="/Admin">Kontrol Paneli</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="LogOut">Çıkış</a>
                            </div>

                        }
                        else if (User.IsInRole("Member"))
                        {
                            <a class="nav-link" href="#" id="dropdownIdprofil" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="fa fa-user mr-2"></span></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownIdprofil">
                                <a class="dropdown-item" href="/Member">Profil</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="LogOut" >Çıkış</a>
                            </div>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Account" asp-action="Login" id="dropdownIdprofil" aria-haspopup="true" aria-expanded="false"> <span class="fa fa-user mr-2"></span></a>
                        }

                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="~/cart" id="dropdownId" aria-haspopup="true" aria-expanded="false"> <span class="fa fa-shopping-bag"></span></a>
                    </li>

                </ul>
            </div>

        </div>
    </nav>
</div>

e-commerce/Project.abznotebook.Web/Areas/Member/Views/Shared/_StandartLayout.cshtml
@*
    Member's Layout
*@

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/lib/Template/theme/content/test.css" rel="stylesheet" />
    <link href="~/lib/Template/theme/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="~/lib/admin-front-packs/dist/css/styles.css" rel="stylesheet" />
    <link href="~/lib/css/abz-stylesheet.css" rel="stylesheet" />

    <title>abz | En iyisi</title>
    <link href="~/img/favicon_transparent.ico" rel="icon" type="image/x-icon" />

</head>
<body>
    <partial name="NavbarPartial" />

    <div class="container" style="width:80%; margin:0 auto">
        <div class="row" style="margin-top:50px">
            <div class="col-md-3 text-center">

                <div class="filter filter-first">
                    <div class="mt-2 mb-4">
                        <div class="custom-control custom-checkbox" style="padding:0; margin:0">
                            <img src="~/img/default_user.png" class="rounded-circle img-fluid img-thumbnail">
                        </div>
                    </div>

                    <div class="mt-2 mb-2">
                        <div class="custom-control custom-checkbox" style="padding:0">
                            <a class="btn btn-primary" asp-controller="Home" asp-action="Index" style="width:80%"><i class="fa fa-user-circle"></i> Profilim</a>
                        </div>
                    </div>

                    <div class="mt-2 mb-2">
                        <div class="custom-control custom-checkbox" style="padding:0">
                            <a class="btn btn-primary" asp-controller="Order" asp-action="Index" style="width:80%"><i class="fa fa-shopping-bag"></i> Siparişlerim</a>
                        </div>
                    </div>

                    <div class="mt-2 mb-2">
                        <div class="custom-control custom-checkbox" style="padding:0">
                            <a class="btn btn-primary" asp-controller="Address" asp-action="Index" style="width:80%"><i class="fa fa-address-book"></i> Adreslerim</a>
                        </div>
                    </div>

                    <div class="mt-2 mb-2">
                        <div class="custom-control custom-checkbox" style="padding:0">
                            <a class="btn btn-primary" asp-controller="Home" asp-action="Index" style="width:80%"><i class="fa fa-circle-o"></i> Ayarlarım</a>
                        </div>
                    </div>

                </div>


                <div class="filter filter-last">
                    <div class="mt-2 mb-2">
                        <div class="custom-control custom-checkbox" style="padding:0">
                            <a href="../../account/logout" class="btn btn-danger" style="width:80%"><i class="fa fa-hourglass-end"></i> Oturumu Kapat</a>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-9" style="border: solid 1px lightgray; border-radius: 7px; padding-top:30px; margin-bottom:50px">

                @RenderBody()

            </div>
        </div>
    </div>











    <!--###########-->
    <!--Eski kodlar-->
    <!--###########-->
    <!--<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">TechnoStore</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>-->
    <!-- Navbar Search-->
    <!--<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">

        </div>
    </form>-->
    <!-- Navbar-->
    <!--<ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Ayarlar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="account/logout">Çıkış</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Ana İşlemler</div>
                        <a class="nav-link" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Hesabım
                        </a>
                        <div class="sb-sidenav-menu-heading">Ana</div>
                        <a class="nav-link collapsed" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Siparişlerim
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Order" asp-action="Index">Tümü</a>
                                <a class="nav-link" href="#">Tamamlananlar</a>
                                <a class="nav-link" href="#">Bekleyenler</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Ayarlar
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" asp-controller="Address" asp-action="AddAddress">
                                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                    Adreslerim
                                </a>

                                <a class="nav-link" href="#">
                                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                    Hesap Ayarları
                                </a>

                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Diğer</div>
                        <a class="nav-link" href="#">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tüm Siparişlerim
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small"></div>
                    <a class="navbar-brand" href="/">Ana Sayfa</a>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>

        </div>
    </div>-->
    @RenderSection("scripts", false)
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/lib/admin-front-packs/dist/js/scripts.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>

</body>
</html>